stages:
- deploy
pack-windows:
  stage: deploy
  script:
    - echo "start build"
    - .\pack.bat
    - echo "end build"
  only:
    - master
  artifacts:
    paths:
    - build\data-manager-desktop-win32-x64\
  tags:
    - data-manager-packing

pack-mac:
  stage: deploy
  script:
    - echo "start build"
    - ./pack.sh
    - echo "end build"
  only:
    - master
  artifacts:
    paths:
    - build/data-manager-desktop-darwin-x64/
  tags:
    - mac
